# Generated by Django 4.1.1 on 2022-09-08 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='employed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('father_name', models.CharField(max_length=255)),
                ('Designation', models.CharField(max_length=255)),
                ('salary', models.PositiveBigIntegerField()),
            ],
            options={
                'db_table': 'employed',
            },
        ),
    ]
