# Generated by Django 4.1.1 on 2022-09-09 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0002_login_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='login',
            name='address',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='login',
            name='password',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='login',
            name='phone_no',
            field=models.PositiveBigIntegerField(blank=True),
        ),
    ]
